import { StyleSheet } from "react-native";
import { COLORS } from "@/styles/colors";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
    paddingHorizontal: 16,
  },
  searchBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.lightGrey,
    borderRadius: 12,
    paddingHorizontal: 12,
    height: 44,
    borderWidth: 1,
    borderColor: COLORS.softGrey,
    marginTop: 15,
  },
  input: {
    flex: 1,
    fontSize: 16,
    color: COLORS.black,
    marginLeft: 8,
  },
  list: {
    paddingTop: 8,
    paddingBottom: 24,
  },
  emptyText: {
    textAlign: "center",
    color: COLORS.darkGrey,
    marginTop: 20,
    marginBottom: 20,
    fontSize: 16,
  },
  card: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.black,
    marginBottom: 8,
    backgroundColor: COLORS.white,
  },
  left: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: 12,
    flex: 1,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: COLORS.black,
  },
  name: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.black,
    flexShrink: 1,
  },
  addButton: {
    backgroundColor: COLORS.green,
    padding: 10,
    borderWidth: 1,
    borderColor: COLORS.black,
    borderRadius: 24,
  },
  removeButton: {
    padding: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.black,
    backgroundColor: COLORS.red,
  },
  resultsTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.black,
    marginBottom: 8,
    marginTop: 8,
    marginLeft: 4,
  },
  friendsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  friendsTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: COLORS.black,
  },
  postCount: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.orange,
  },
  currentUserHighlight: {
    backgroundColor: COLORS.seashell,
    borderColor: COLORS.orange,
    borderWidth: 1.5,
  },
  streak: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.seashell,
    borderColor: COLORS.orange,
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  streakText: {
    marginLeft: 4,
    color: COLORS.orange,
    fontWeight: "600",
    fontSize: 12,
  },
});
