import { StyleSheet } from "react-native";
import { COLORS } from "@/styles/colors";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  content: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 25,
    marginBottom: 25,
  },
  formContainer: {
    backgroundColor: COLORS.white,
    padding: 24,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: COLORS.black,
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
    justifyContent: "space-between",
  },
  imageSection: {
    height: 350,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.black,
    backgroundColor: COLORS.lightGrey,
    overflow: "hidden",
    marginBottom: 16,
  },
  imageButton: {
    flex: 1,
    backgroundColor: COLORS.orange,
    justifyContent: "center",
    alignItems: "center",
    gap: 24,
  },
  halfImageButtonTop: {
    flex: 1,
    backgroundColor: COLORS.orange,
    justifyContent: "center",
    alignItems: "center",
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    gap: 16,
  },
  halfImageButtonBottom: {
    flex: 1,
    backgroundColor: COLORS.orange,
    justifyContent: "center",
    alignItems: "center",
    gap: 16,
  },
  iconContainer: {
    width: 90,
    height: 90,
    borderRadius: 64,
    backgroundColor: "rgba(255, 255, 255, 0.2)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.white,
  },
  imageButtonText: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
  },
  selectedImageContainer: {
    flex: 1,
    position: "relative",
  },
  selectedImage: {
    flex: 1,
  },
  removeImageButton: {
    position: "absolute",
    top: 12,
    right: 12,
    backgroundColor: COLORS.orange,
    borderRadius: 24,
    width: 48,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  descriptionContainer: {
    marginTop: 16,
  },
  descriptionInput: {
    height: 100,
    fontSize: 16,
    color: COLORS.black,
    padding: 12,
    lineHeight: 24,
    borderWidth: 1,
    borderColor: COLORS.black,
    borderRadius: 12,
    backgroundColor: COLORS.white,
  },
  postButton: {
    backgroundColor: COLORS.orange,
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginTop: 24,
    borderWidth: 1,
    borderColor: COLORS.black,
  },
  postButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "600",
  },
  successContainer: {
    flex: 1,
    backgroundColor: COLORS.white,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  successContent: {
    alignItems: "center",
    width: "100%",
    maxWidth: 400,
    gap: 16,
  },
  successTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.black,
  },
  successText: {
    fontSize: 16,
    color: COLORS.darkGrey,
    textAlign: "center",
  },
  successButton: {
    marginTop: 16,
    height: 56,
    width: "100%",
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1.5,
    borderColor: COLORS.black,
    backgroundColor: COLORS.orange,
  },
  successButtonText: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: "600",
  },
});
